[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
epplex_core = "3mYw5ZvWhmYRgB3pPqj6mcsRndUJWiAFwkHzfNj1m1Ct"

[programs.localnet]
epplex_core = "2qie61sigqbg3xkh3UkpLPJppjbjKQa8FStcB5k5XYff"
epplex_metadata = "37ZXXzuuiTPsH7upkRMq897M1nhXq1HP3fBSGB1hpbQ1"
epplex_mint = "9y9Y8sGsuv7k3WGyrrGiTjpT1ugzf9hBaAvkWemtwqkL"

[programs.mainnet]
epplex_core = "epPgfrTRUdijJdkjn6EYBNsPrf8YSV7JeUGGhWSwkex"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sleyn/.config/solana/id.json"

[scripts]
bd = "anchor build && anchor deploy && anchor run copy-to-app"
copy-to-app = "mkdir -p client/idl && cp target/idl/epplex_core.json app/client/idl/ephemerality.json && cp target/types/epplex_core.ts app/client/idl/ephemeralityTypes.ts"
depl = "anchor deploy && anchor run copy-to-app"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 ./tests/*spec.ts"
