[features]
seeds = false

[programs.localnet]
ep_mint = "DWQ12BSvpNq6AxX18Xgm72avoCT8nL8G7R886NeiLFeN"
ephemerality = "7N839QzgShmkazepHcHx87u4gg29jTsYYeY8rNV7XffR"

[programs.devnet]
ephemerality = "7N839QzgShmkazepHcHx87u4gg29jTsYYeY8rNV7XffR"

[programs.mainnet]
ephemerality = "7N839QzgShmkazepHcHx87u4gg29jTsYYeY8rNV7XffR"

[provider]
cluster = "Localnet"
wallet = "/home/sleyn/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-to-app = "mkdir -p client/idl && cp target/idl/ephemerality.json app/client/idl/ephemerality.json && cp target/types/ephemerality.ts app/client/idl/ephemeralityTypes.ts"
bd = "anchor build && anchor deploy && anchor run copy-to-app"
depl = "anchor deploy && anchor run copy-to-app"