[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
epplex_burger = "epBuJysRKuFMMWTWoX6ZKPz5WTZWb98mDqn1emVj84n"
epplex_core = "epCoD6BqcNinLvKN3KkY55vk4Kxs3W1JTENs1xqWUTg"
epplex_shared = "epShtSs6bXafJMhjKCJM8CLyZJSDvzVGwfmEUiXTgqJ"

[programs.localnet]
epplex_burger = "epBuJysRKuFMMWTWoX6ZKPz5WTZWb98mDqn1emVj84n"
epplex_core = "epCoD6BqcNinLvKN3KkY55vk4Kxs3W1JTENs1xqWUTg"
epplex_shared = "epShtSs6bXafJMhjKCJM8CLyZJSDvzVGwfmEUiXTgqJ"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "https://api.devnet.solana.com"
cluster = "http://127.0.0.1:8899"
wallet = "/home/fzzyyti/.config/solana/test.json"

[scripts]
test-individual = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 ./tests/testIndividualMint.ts"
test-collection = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 ./tests/testCollectionMint.ts"
test-all = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 ./tests/*.spec.ts"

copy-burger-sdk   = "cp target/idl/epplex_burger.json    ../sdk/src/idl/epplex_burger.json       && cp target/types/epplex_burger.ts    ../sdk/src/types/epplexBurgerTypes.ts"
copy-core-sdk     = "cp target/idl/epplex_core.json      ../sdk/src/idl/epplex_core.json         && cp target/types/epplex_core.ts      ../sdk/src/types/epplexCoreTypes.ts"
copy-to-sdk = "anchor run copy-core-sdk && anchor run copy-mint-sdk && anchor run copy-burger-sdk"

#copy-burger = "cp target/idl/epplex_burger.json app/client/idl/epplex_burger.json && cp target/types/epplex_burger.ts app/client/idl/epplexBurgerTypes.ts"
#copy-mint = "cp target/idl/epplex_mint.json app/client/idl/epplex_mint.json && cp target/types/epplex_mint.ts app/client/idl/epplexMintTypes.ts"
#copy-core = "cp target/idl/epplex_core.json app/client/idl/epplex_core.json && cp target/types/epplex_core.ts app/client/idl/epplexCoreTypes.ts"
#copy-to-app = "anchor run copy-core && anchor run copy-mint && anchor run copy-burger"

# THIS SECTION IS MOST LIKELY DEPRECATED
build-burger = "anchor build -p epplex_burger && anchor deploy -p epplex_burger && anchor run copy-burger"
build-core = "anchor build -p epplex_core && anchor deploy -p epplex_core && anchor run copy-core"
#bd = "anchor build && anchor deploy && anchor run copy-to-app"
bd = "anchor run build-burger && anchor run build-core"
depl = "anchor deploy && anchor run copy-to-app"